export const APPEARANCE_THEMES_DEFINITIONS = {
    'studio-dark': { 
        name: 'Studio Dark',
        vars: {
            '--bg-chassis': '#101114',
            '--bg-panel': '#1A1C20',
            '--bg-panel-dark': '#000000',
            '--bg-control': '#1C1F23',
            '--border-color': '#2A2E33',
            '--border-color-light': '#484D5C',
            '--border-color-darker': '#000',
            '--text-light': '#DCE0E6',
            '--text-dark': '#111111',
            '--text-muted': '#6A7185',
            '--text-screen': '#E0E6F0',
            '--text-screen-glow': '0 0 5px rgba(224, 230, 240, 0.2)',
            '--color-mute': '#E53935',
            '--font-main': "'Roboto', sans-serif",
            '--font-mono': "'Roboto Mono', monospace",
            '--shadow-deep': 'rgba(0,0,0,0.8)',
            '--highlight-soft': 'rgba(255,255,255,0.08)',
            '--pianoroll-white-key': '#cdd3de',
            '--pianoroll-white-key-gradient': '#a9b1c2',
            '--pianoroll-black-key': '#1C1F23',
            '--pianoroll-black-key-gradient': '#101114',
            '--pianoroll-white-key-text': '#0A0B0C',
            '--pianoroll-black-key-text': '#DCE0E6',
            '--pianoroll-white-key-border': '#6A7185',
            '--pianoroll-black-key-border': '#000000',
            '--pianoroll-grid-bar': 'rgba(255,255,255,0.20)',
            '--pianoroll-grid-beat': 'rgba(255,255,255,0.15)',
            '--pianoroll-grid-step': 'rgba(255,255,255,0.10)',
            '--pianoroll-scale-highlight-dark': 'rgba(255,255,255,0.07)',
            '--pianoroll-scale-highlight-light': 'rgba(255,255,255,0.03)',
            '--sequencer-step-light': '#1F2228',
            '--sequencer-step-dark': '#16181C',
        }
    },
    'ghost': {
        name: 'Ghost',
        vars: {
            '--accent-color': '#00d8ff',
            '--accent-color-active': '#80ebff',
            '--accent-rgb': '0, 216, 255',
            '--bg-chassis': `
                radial-gradient(ellipse 80% 50% at 50% 50%, rgba(200, 240, 255, 0.15), transparent),
                linear-gradient(0deg, rgba(180, 210, 255, 0.05) 1px, transparent 1px),
                linear-gradient(90deg, rgba(180, 210, 255, 0.05) 1px, transparent 1px),
                #1a2035`,
            '--bg-panel': 'rgba(240, 245, 255, 0.9)',
            '--bg-panel-dark': 'rgba(210, 220, 240, 0.95)',
            '--bg-control': '#343A46',
            '--border-color': 'rgba(170, 190, 220, 0.5)',
            '--border-color-light': 'rgba(200, 220, 255, 0.7)',
            '--border-color-darker': 'rgba(150, 170, 200, 0.3)',
            '--text-light': '#212529',
            '--text-dark': '#000000',
            '--text-muted': '#5A6470',
            '--text-screen': 'var(--accent-color)',
            '--text-screen-glow': '0 0 8px rgba(var(--accent-rgb), 0.7)',
            '--color-mute': '#e53935',
            '--font-main': "'Roboto', sans-serif",
            '--font-mono': "'Roboto Mono', monospace",
            '--shadow-deep': 'rgba(0,0,0,0.7)',
            '--highlight-soft': 'rgba(0,0,0,0.1)',
            '--pianoroll-white-key': '#495057',
            '--pianoroll-white-key-gradient': '#343a40',
            '--pianoroll-black-key': '#212529',
            '--pianoroll-black-key-gradient': '#111315',
            '--pianoroll-white-key-text': '#dee2e6',
            '--pianoroll-black-key-text': '#adb5bd',
            '--pianoroll-white-key-border': '#212529',
            '--pianoroll-black-key-border': '#000000',
            '--pianoroll-grid-bar': 'rgba(0,0,0,0.2)',
            '--pianoroll-grid-beat': 'rgba(0,0,0,0.1)',
            '--pianoroll-grid-step': 'rgba(0,0,0,0.05)',
            '--pianoroll-scale-highlight-dark': 'rgba(0, 216, 255, 0.1)',
            '--pianoroll-scale-highlight-light': 'rgba(0, 216, 255, 0.05)',
            '--sequencer-step-light': 'rgba(255, 255, 255, 0.1)',
            '--sequencer-step-dark': 'rgba(255, 255, 255, 0.05)',
        }
    },
    'studio-88': {
        name: "Studio '88",
        vars: {
            '--bg-chassis': '#282828',
            '--bg-panel': '#3c3c3c',
            '--bg-panel-dark': '#1e1e1e',
            '--bg-control': '#505050',
            '--border-color': '#666666',
            '--border-color-light': '#7a7a7a',
            '--border-color-darker': '#000000',
            '--text-light': '#f3eadd',
            '--text-dark': '#282828',
            '--text-muted': '#9d9181',
            '--text-screen': '#ffb74d',
            '--text-screen-glow': '0 0 8px rgba(255, 183, 77, 0.3)',
            '--color-mute': '#e57373',
            '--font-main': "'Roboto', sans-serif",
            '--font-mono': "'Roboto Mono', monospace",
            '--shadow-deep': 'rgba(0,0,0,0.7)',
            '--highlight-soft': 'rgba(255, 255, 255, 0.1)',
            '--pianoroll-white-key': '#e0d8cc',
            '--pianoroll-white-key-gradient': '#c1b8a9',
            '--pianoroll-black-key': '#3c3c3c',
            '--pianoroll-black-key-gradient': '#282828',
            '--pianoroll-white-key-text': '#282828',
            '--pianoroll-black-key-text': '#f3eadd',
            '--pianoroll-white-key-border': '#9d9181',
            '--pianoroll-black-key-border': '#1e1e1e',
            '--sequencer-step-light': '#323232',
            '--sequencer-step-dark': '#282828',
        }
    },
    'cyber-neon': {
        name: 'Cyber Neon',
        vars: {
            '--bg-chassis': '#02010A',
            '--bg-panel': '#08041C',
            '--bg-panel-dark': '#000000',
            '--bg-control': '#120A33',
            '--border-color': '#3A2B8C',
            '--border-color-light': '#4D5E8C',
            '--border-color-darker': '#000',
            '--text-light': '#E6DFFF',
            '--text-dark': '#0A0F1E',
            '--text-muted': '#9788DD',
            '--text-screen': '#E0E0FF',
            '--text-screen-glow': '0 0 10px rgba(var(--accent-rgb), 0.3)',
            '--color-mute': '#FF4D88',
            '--font-main': "'Roboto', sans-serif",
            '--font-mono': "'Roboto Mono', monospace",
            '--shadow-deep': 'rgba(0,0,0,0.8)',
            '--highlight-soft': 'rgba(255,255,255,0.15)',
            '--pianoroll-white-key': '#c2badd',
            '--pianoroll-white-key-gradient': '#9788DD',
            '--pianoroll-black-key': '#120A33',
            '--pianoroll-black-key-gradient': '#08041C',
            '--pianoroll-white-key-text': '#02010A',
            '--pianoroll-black-key-text': '#E6DFFF',
            '--pianoroll-white-key-border': '#4D5E8C',
            '--pianoroll-black-key-border': '#000000',
            '--pianoroll-grid-bar': 'rgba(var(--accent-rgb), 0.25)',
            '--pianoroll-grid-beat': 'rgba(var(--accent-rgb), 0.15)',
            '--pianoroll-grid-step': 'rgba(var(--accent-rgb), 0.08)',
            '--pianoroll-scale-highlight-dark': 'rgba(var(--accent-rgb), 0.1)',
            '--pianoroll-scale-highlight-light': 'rgba(var(--accent-rgb), 0.05)',
            '--sequencer-step-light': '#0A061F',
            '--sequencer-step-dark': '#02010A',
        }
    },
    'minimalist-light': {
        name: 'Minimalist Light',
        vars: {
            '--bg-chassis': '#e0e0e0',
            '--bg-panel': '#f5f5f5',
            '--bg-panel-dark': '#d1d1d1',
            '--bg-control': '#e0e0e0',
            '--border-color': '#b0b0b0',
            '--border-color-light': '#cccccc',
            '--border-color-darker': '#c2c2c2',
            '--text-light': '#212121',
            '--text-dark': '#ffffff',
            '--text-muted': '#616161',
            '--text-screen': '#000000',
            '--text-screen-glow': 'none',
            '--color-mute': '#d32f2f',
            '--font-main': "'Roboto', sans-serif",
            '--font-mono': "'Roboto Mono', monospace",
            '--shadow-deep': 'rgba(0,0,0,0.15)',
            '--highlight-soft': 'rgba(0,0,0,0.1)',
            '--pianoroll-white-key': '#FFFFFF',
            '--pianoroll-white-key-gradient': '#E0E0E0',
            '--pianoroll-black-key': '#757575',
            '--pianoroll-black-key-gradient': '#616161',
            '--pianoroll-white-key-text': '#424242',
            '--pianoroll-black-key-text': '#eeeeee',
            '--pianoroll-white-key-border': '#bdbdbd',
            '--pianoroll-black-key-border': '#424242',
            '--pianoroll-grid-bar': 'rgba(0,0,0,0.12)',
            '--pianoroll-grid-beat': 'rgba(0,0,0,0.08)',
            '--pianoroll-grid-step': 'rgba(0,0,0,0.04)',
            '--pianoroll-scale-highlight-dark': 'rgba(0,0,0,0.08)',
            '--pianoroll-scale-highlight-light': 'rgba(0,0,0,0.04)',
            '--sequencer-step-light': '#e6e6e6',
            '--sequencer-step-dark': '#dcdcdc',
        }
    },
    'blueprint': {
        name: 'Blueprint',
        vars: {
            '--bg-chassis': '#0A192F',
            '--bg-panel': '#112240',
            '--bg-panel-dark': '#020C1B',
            '--bg-control': '#173A5E',
            '--border-color': '#60A5FA',
            '--border-color-light': '#B0E0E6',
            '--border-color-darker': '#0A192F',
            '--text-light': '#F0F8FF',
            '--text-dark': '#0A192F',
            '--text-muted': '#9DD8F5',
            '--text-screen': '#FFFFFF',
            '--text-screen-glow': '0 0 6px rgba(255,255,255,0.3)',
            '--color-mute': '#FF6347',
            '--font-main': "'Roboto Mono', monospace",
            '--font-mono': "'Roboto Mono', monospace",
            '--shadow-deep': 'rgba(0,0,0,0.6)',
            '--highlight-soft': 'rgba(255,255,255,0.15)',
            '--pianoroll-white-key': '#F0F8FF',
            '--pianoroll-white-key-gradient': '#B0E0E6',
            '--pianoroll-black-key': '#173A5E',
            '--pianoroll-black-key-gradient': '#112240',
            '--pianoroll-white-key-text': '#0A192F',
            '--pianoroll-black-key-text': '#F0F8FF',
            '--pianoroll-white-key-border': '#60A5FA',
            '--pianoroll-black-key-border': '#020C1B',
            '--pianoroll-grid-bar': 'rgba(255,255,255,0.2)',
            '--pianoroll-grid-beat': 'rgba(255,255,255,0.12)',
            '--pianoroll-grid-step': 'rgba(255,255,255,0.06)',
            '--pianoroll-scale-highlight-dark': 'rgba(255,255,255,0.1)',
            '--pianoroll-scale-highlight-light': 'rgba(255,255,255,0.05)',
            '--sequencer-step-light': '#0F1E33',
            '--sequencer-step-dark': '#0A192F',
        }
    },
    'nordic-night': {
        name: 'Nordic Night',
        vars: {
            '--bg-chassis': '#1E222A',
            '--bg-panel': '#292E39',
            '--bg-panel-dark': '#1A1D23',
            '--bg-control': '#3B4252',
            '--border-color': '#5E81AC',
            '--border-color-light': '#81A1C1',
            '--border-color-darker': '#1E222A',
            '--text-light': '#ECEFF4',
            '--text-dark': '#1E222A',
            '--text-muted': '#D8DEE9',
            '--text-screen': '#ECEFF4',
            '--text-screen-glow': '0 0 5px rgba(236, 239, 244, 0.15)',
            '--color-mute': '#BF616A',
            '--font-main': "'Roboto', sans-serif",
            '--font-mono': "'Roboto Mono', monospace",
            '--shadow-deep': 'rgba(0,0,0,0.6)',
            '--highlight-soft': 'rgba(255,255,255,0.08)',
            '--pianoroll-white-key': '#ECEFF4',
            '--pianoroll-white-key-gradient': '#D8DEE9',
            '--pianoroll-black-key': '#3B4252',
            '--pianoroll-black-key-gradient': '#292E39',
            '--pianoroll-white-key-text': '#1E222A',
            '--pianoroll-black-key-text': '#ECEFF4',
            '--pianoroll-white-key-border': '#5E81AC',
            '--pianoroll-black-key-border': '#1A1D23',
            '--pianoroll-grid-bar': 'rgba(255,255,255,0.15)',
            '--pianoroll-grid-beat': 'rgba(255,255,255,0.1)',
            '--pianoroll-grid-step': 'rgba(255,255,255,0.05)',
            '--pianoroll-scale-highlight-dark': 'rgba(255,255,255,0.07)',
            '--pianoroll-scale-highlight-light': 'rgba(255,255,255,0.03)',
            '--sequencer-step-light': '#292E39',
            '--sequencer-step-dark': '#1E222A',
        }
    },
    'ableton-grey': {
        name: 'DAW Grey',
        vars: {
            '--bg-chassis': '#3d3d3d',
            '--bg-panel': '#535353',
            '--bg-panel-dark': '#2a2a2a',
            '--bg-control': '#707070',
            '--border-color': '#909090',
            '--border-color-light': '#ababab',
            '--border-color-darker': '#1a1a1a',
            '--text-light': '#f0f0f0',
            '--text-dark': '#111111',
            '--text-muted': '#b0b0b0',
            '--text-screen': '#ffffff',
            '--text-screen-glow': 'none',
            '--color-mute': '#ff6b6b',
            '--font-main': "'Roboto', sans-serif",
            '--font-mono': "'Roboto Mono', monospace",
            '--shadow-deep': 'rgba(0,0,0,0.5)',
            '--highlight-soft': 'rgba(255,255,255,0.2)',
            '--pianoroll-white-key': '#cccccc',
            '--pianoroll-white-key-gradient': '#b3b3b3',
            '--pianoroll-black-key': '#4f4f4f',
            '--pianoroll-black-key-gradient': '#3a3a3a',
            '--pianoroll-white-key-text': '#2a2a2a',
            '--pianoroll-black-key-text': '#f0f0f0',
            '--pianoroll-white-key-border': '#909090',
            '--pianoroll-black-key-border': '#2a2a2a',
            '--pianoroll-grid-bar': 'rgba(0,0,0,0.2)',
            '--pianoroll-grid-beat': 'rgba(0,0,0,0.15)',
            '--pianoroll-grid-step': 'rgba(0,0,0,0.1)',
            '--pianoroll-scale-highlight-dark': 'rgba(0,0,0,0.1)',
            '--pianoroll-scale-highlight-light': 'rgba(255,255,255,0.04)',
            '--sequencer-step-light': '#4a4a4a',
            '--sequencer-step-dark': '#3d3d3d',
        }
    }
};

export const APPEARANCE_THEMES = Object.fromEntries(
  Object.entries(APPEARANCE_THEMES_DEFINITIONS).map(([key, { name }]) => [key, { name }])
);

export const ACCENT_THEMES = {
    'studio-amber': { 
        name: 'Studio Amber',
        '--accent-color': '#FFB800',
        '--accent-color-active': '#FFD040',
        '--accent-rgb': '255, 184, 0',
    },
    'studio-orange': {
        name: 'Studio Orange',
        '--accent-color': '#E67E22',
        '--accent-color-active': '#F39C12',
        '--accent-rgb': '230, 126, 34',
    },
    'cyber-magenta': {
        name: 'Cyber Magenta',
        '--accent-color': '#FF00FF',
        '--accent-color-active': '#FF69B4',
        '--accent-rgb': '255, 0, 255',
    },
    'corporate-blue': {
        name: 'Corporate Blue',
        '--accent-color': '#0052CC',
        '--accent-color-active': '#4C9AFF',
        '--accent-rgb': '0, 82, 204',
    },
    'blueprint-white': {
        name: 'Blueprint White',
        '--accent-color': '#FFFFFF',
        '--accent-color-active': '#E0E0E0',
        '--accent-rgb': '255, 255, 255',
    },
    'nordic-ice': {
        name: 'Nordic Ice',
        '--accent-color': '#88C0D0',
        '--accent-color-active': '#A3D4E5',
        '--accent-rgb': '136, 192, 208',
    },
    'daw-cyan': {
        name: 'DAW Cyan',
        '--accent-color': '#00d8ff',
        '--accent-color-active': '#80ebff',
        '--accent-rgb': '0, 216, 255',
    }
};

export function applyTheme(themeKey: keyof typeof APPEARANCE_THEMES_DEFINITIONS) {
    const theme = APPEARANCE_THEMES_DEFINITIONS[themeKey];
    if (!theme) return;

    const root = document.body;
    
    // Add a class to the body for theme-specific CSS rules (like backdrop-filter)
    root.className = themeKey;

    Object.entries(theme.vars).forEach(([key, value]) => {
        root.style.setProperty(key, value);
    });
}