import { InstrumentPreset, LFOParams } from '../types';

const NEUTRAL_LFO: LFOParams = { waveform: 'triangle', rate: 1, depth: 0, destination: 'none', rateSync: false, rateDivision: 1, retrigger: false };
const createPreset = (type: any, name: string, params: any): InstrumentPreset => ({ type, name, params });

const KICK_PRESETS: InstrumentPreset[] = [
    createPreset('kick', 'DHT - Concrete Kick', { tune: 44, decay: 0.28, impact: 98, tone: 70, character: 65, ampEnv: { attack: 0.001, decay: 0.28, sustain: 0, release: 0.1 }, filter: { type: 'lowpass', cutoff: 16000, resonance: 2 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('kick', 'DHT - Sub Rumble', { tune: 38, decay: 1.8, impact: 85, tone: 15, character: 60, ampEnv: { attack: 0.002, decay: 1.8, sustain: 0, release: 1.0 }, filter: { type: 'lowpass', cutoff: 180, resonance: 8 }, lfo1: { ...NEUTRAL_LFO, destination: 'filter.cutoff', rate: 0.1, rateSync: false, depth: 250 }, lfo2: NEUTRAL_LFO }),
    createPreset('kick', 'DHT - Distorted Slam', { tune: 48, decay: 0.4, impact: 100, tone: 45, character: 92, ampEnv: { attack: 0.001, decay: 0.4, sustain: 0, release: 0.2 }, filter: { type: 'lowpass', cutoff: 12000, resonance: 4 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('kick', 'DHT - Short Tick', { tune: 60, decay: 0.12, impact: 80, tone: 95, character: 5, ampEnv: { attack: 0.001, decay: 0.12, sustain: 0, release: 0.05 }, filter: { type: 'lowpass', cutoff: 20000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('kick', 'DHT - Filtered Zap', { tune: 55, decay: 0.2, impact: 70, tone: 100, character: 0, ampEnv: { attack: 0.001, decay: 0.2, sustain: 0, release: 0.1 }, filter: { type: 'lowpass', cutoff: 600, resonance: 12 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('kick', 'DHT - 909 Overdrive', { tune: 46, decay: 0.45, impact: 92, tone: 75, character: 70, ampEnv: { attack: 0.001, decay: 0.45, sustain: 0, release: 0.2 }, filter: { type: 'lowpass', cutoff: 19000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('kick', 'DHT - Deep Pulse', { tune: 36, decay: 1.1, impact: 78, tone: 30, character: 15, ampEnv: { attack: 0.001, decay: 1.1, sustain: 0, release: 0.6 }, filter: { type: 'lowpass', cutoff: 4000, resonance: 2 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('kick', 'DHT - Industrial Hit', { tune: 52, decay: 0.3, impact: 100, tone: 50, character: 100, ampEnv: { attack: 0.001, decay: 0.3, sustain: 0, release: 0.1 }, filter: { type: 'lowpass', cutoff: 20000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('kick', 'DHT - Gabber Zap', { tune: 65, decay: 0.25, impact: 100, tone: 100, character: 80, ampEnv: { attack: 0.001, decay: 0.25, sustain: 0, release: 0.1 }, filter: { type: 'lowpass', cutoff: 20000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('kick', 'DHT - Muted Thump', { tune: 40, decay: 0.25, impact: 88, tone: 20, character: 10, ampEnv: { attack: 0.001, decay: 0.25, sustain: 0, release: 0.1 }, filter: { type: 'lowpass', cutoff: 800, resonance: 3 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('kick', 'DHT - Resonant Body', { tune: 43, decay: 0.5, impact: 88, tone: 60, character: 30, ampEnv: { attack: 0.001, decay: 0.5, sustain: 0, release: 0.2 }, filter: { type: 'lowpass', cutoff: 350, resonance: 11 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('kick', 'DHT - Warehouse', { tune: 41, decay: 0.7, impact: 94, tone: 40, character: 78, ampEnv: { attack: 0.001, decay: 0.7, sustain: 0, release: 0.3 }, filter: { type: 'lowpass', cutoff: 13000, resonance: 3.5 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('kick', 'DHT - Hardtek', { tune: 50, decay: 0.2, impact: 100, tone: 85, character: 85, ampEnv: { attack: 0.001, decay: 0.2, sustain: 0, release: 0.1 }, filter: { type: 'lowpass', cutoff: 20000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('kick', 'DHT - Minimal Click', { tune: 62, decay: 0.1, impact: 75, tone: 100, character: 0, ampEnv: { attack: 0.001, decay: 0.1, sustain: 0, release: 0.05 }, filter: { type: 'lowpass', cutoff: 20000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('kick', 'DHT - Tunnel Rumble', { tune: 37, decay: 2.5, impact: 80, tone: 10, character: 70, ampEnv: { attack: 0.005, decay: 2.5, sustain: 0, release: 1.5 }, filter: { type: 'lowpass', cutoff: 150, resonance: 9 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
];

const HAT_PRESETS: InstrumentPreset[] = [
    createPreset('hat', 'DHT - Rusted Hat', { tone: 8500, decay: 0.06, character: 90, spread: 2.5, ampEnv: { attack: 0.001, decay: 0.06, sustain: 0, release: 0.04 }, filter: { type: 'highpass', cutoff: 6000, resonance: 4 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('hat', 'DHT - Metallic Ride', { tone: 6000, decay: 0.8, character: 100, spread: 1.2, ampEnv: { attack: 0.001, decay: 0.8, sustain: 0, release: 0.4 }, filter: { type: 'bandpass', cutoff: 7500, resonance: 15 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('hat', 'DHT - Tight 909', { tone: 9500, decay: 0.03, character: 80, spread: 1.8, ampEnv: { attack: 0.001, decay: 0.03, sustain: 0, release: 0.02 }, filter: { type: 'highpass', cutoff: 7500, resonance: 2 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('hat', 'DHT - Sizzle', { tone: 11000, decay: 0.5, character: 65, spread: 1.5, ampEnv: { attack: 0.01, decay: 0.5, sustain: 0, release: 0.2 }, filter: { type: 'highpass', cutoff: 9000, resonance: 3 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('hat', 'DHT - Dark Shaker', { tone: 7000, decay: 0.09, character: 40, spread: 3.0, ampEnv: { attack: 0.005, decay: 0.09, sustain: 0, release: 0.06 }, filter: { type: 'lowpass', cutoff: 11000, resonance: 5 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('hat', 'DHT - Industrial Tin', { tone: 4500, decay: 0.04, character: 95, spread: 1.1, ampEnv: { attack: 0.001, decay: 0.04, sustain: 0, release: 0.03 }, filter: { type: 'bandpass', cutoff: 5500, resonance: 14 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('hat', 'DHT - Fast Filtered', { tone: 9000, decay: 0.08, character: 50, spread: 2.0, ampEnv: { attack: 0.001, decay: 0.08, sustain: 0, release: 0.05 }, filter: { type: 'highpass', cutoff: 8000, resonance: 1 }, lfo1: { ...NEUTRAL_LFO, destination: 'filter.cutoff', rate: 16, rateSync: false, depth: 3000 }, lfo2: NEUTRAL_LFO }),
    createPreset('hat', 'DHT - Panning Tick', { tone: 12000, decay: 0.02, character: 20, spread: 1.3, ampEnv: { attack: 0.001, decay: 0.02, sustain: 0, release: 0.02 }, filter: { type: 'highpass', cutoff: 10000, resonance: 1 }, lfo1: { ...NEUTRAL_LFO, destination: 'pan', rate: 0.2, rateSync: false, depth: 800 }, lfo2: NEUTRAL_LFO }),
    createPreset('hat', 'DHT - Trash Can Lid', { tone: 7200, decay: 0.25, character: 100, spread: 3.8, ampEnv: { attack: 0.001, decay: 0.25, sustain: 0, release: 0.1 }, filter: { type: 'highpass', cutoff: 3000, resonance: 6 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('hat', 'DHT - Glitch Hat', { tone: 10000, decay: 0.05, character: 60, spread: 1.0, ampEnv: { attack: 0.001, decay: 0.05, sustain: 0, release: 0.05 }, filter: { type: 'notch', cutoff: 6000, resonance: 18 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('hat', 'DHT - Crisp 808', { tone: 10500, decay: 0.03, character: 10, spread: 2.2, ampEnv: { attack: 0.001, decay: 0.03, sustain: 0, release: 0.02 }, filter: { type: 'highpass', cutoff: 9000, resonance: 1.2 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('hat', 'DHT - Airy Open Hat', { tone: 11000, decay: 0.6, character: 5, spread: 3.0, ampEnv: { attack: 0.005, decay: 0.6, sustain: 0, release: 0.2 }, filter: { type: 'highpass', cutoff: 8000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('hat', 'DHT - Short Crash', { tone: 7000, decay: 1.2, character: 90, spread: 1.5, ampEnv: { attack: 0.001, decay: 1.2, sustain: 0, release: 0.5 }, filter: { type: 'highpass', cutoff: 500, resonance: 5 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('hat', 'DHT - Tambourine', { tone: 9000, decay: 0.1, character: 85, spread: 1.1, ampEnv: { attack: 0.001, decay: 0.1, sustain: 0, release: 0.08 }, filter: { type: 'bandpass', cutoff: 9000, resonance: 11 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('hat', 'DHT - Lo-Fi Grit', { tone: 6500, decay: 0.07, character: 95, spread: 2.8, ampEnv: { attack: 0.001, decay: 0.07, sustain: 0, release: 0.05 }, filter: { type: 'bandpass', cutoff: 7000, resonance: 7 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
];

const RUIN_PRESETS: InstrumentPreset[] = [
    createPreset('ruin', 'DHT - Sub Stab', { pitch: 36, algorithm: 'distort_fold', timbre: 40, drive: 60, fold: 20, attack: 0.001, decay: 0.18, filter: { type: 'lowpass', cutoff: 450, resonance: 8 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('ruin', 'DHT - Aggro Bass', { pitch: 36, algorithm: 'overload', timbre: 70, drive: 85, fold: 70, attack: 0.002, decay: 0.22, filter: { type: 'lowpass', cutoff: 900, resonance: 5 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('ruin', 'DHT - Fold Perc', { pitch: 60, algorithm: 'distort_fold', timbre: 80, drive: 30, fold: 90, attack: 0.001, decay: 0.08, filter: { type: 'bandpass', cutoff: 2500, resonance: 10 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('ruin', 'DHT - FM Drone Hit', { pitch: 48, algorithm: 'feedback_pm', timbre: 90, drive: 10, fold: 0, attack: 0.001, decay: 0.4, filter: { type: 'lowpass', cutoff: 4000, resonance: 3 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('ruin', 'DHT - Industrial Impact', { pitch: 40, algorithm: 'overload', timbre: 90, drive: 90, fold: 90, attack: 0.001, decay: 0.3, filter: { type: 'lowpass', cutoff: 2000, resonance: 6 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('ruin', 'DHT - Screech Bass', { pitch: 48, algorithm: 'distort_fold', timbre: 95, drive: 90, fold: 80, attack: 0.001, decay: 0.15, filter: { type: 'bandpass', cutoff: 1800, resonance: 9 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('ruin', 'DHT - Broken Speaker', { pitch: 30, algorithm: 'overload', timbre: 100, drive: 100, fold: 100, attack: 0.001, decay: 0.2, filter: { type: 'lowpass', cutoff: 1500, resonance: 5 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('ruin', 'DHT - Resonant Drone', { pitch: 36, algorithm: 'feedback_pm', timbre: 98, drive: 50, fold: 10, attack: 0.1, decay: 1.5, filter: { type: 'lowpass', cutoff: 500, resonance: 12 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('ruin', 'DHT - Short Zap', { pitch: 72, algorithm: 'distort_fold', timbre: 70, drive: 80, fold: 95, attack: 0.001, decay: 0.05, filter: { type: 'highpass', cutoff: 1000, resonance: 4 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('ruin', 'DHT - Gritty Tom', { pitch: 40, algorithm: 'distort_fold', timbre: 20, drive: 70, fold: 40, attack: 0.001, decay: 0.12, filter: { type: 'lowpass', cutoff: 1200, resonance: 8 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
];

const ARCANE_PRESETS: InstrumentPreset[] = [
    createPreset('arcane', 'DHT - Warehouse Stab', { osc1_shape: 35, osc2_shape: 85, osc2_pitch: 12, osc2_fine: 0, mode: 'pm', mod_amount: 45, fold: 20, spread: 8, ampEnv: { attack: 0.001, decay: 0.3, sustain: 0, release: 0.2 }, filter: { type: 'lowpass', cutoff: 2800, resonance: 7 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('arcane', 'DHT - Dissonant Bell', { osc1_shape: 10, osc2_shape: 90, osc2_pitch: 19, osc2_fine: 15, mode: 'ring', mod_amount: 80, fold: 0, spread: 0, ampEnv: { attack: 0.001, decay: 0.4, sustain: 0, release: 0.3 }, filter: { type: 'highpass', cutoff: 500, resonance: 2 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('arcane', 'DHT - Sync Lead Stab', { osc1_shape: 80, osc2_shape: 20, osc2_pitch: 7, osc2_fine: 0, mode: 'hard_sync', mod_amount: 60, fold: 10, spread: 0, ampEnv: { attack: 0.001, decay: 0.2, sustain: 0, release: 0.1 }, filter: { type: 'lowpass', cutoff: 5000, resonance: 5 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('arcane', 'DHT - Folded Metal', { osc1_shape: 50, osc2_shape: 50, osc2_pitch: 24, osc2_fine: 0, mode: 'add', mod_amount: 100, fold: 95, spread: 20, ampEnv: { attack: 0.001, decay: 0.15, sustain: 0, release: 0.1 }, filter: { type: 'bandpass', cutoff: 4000, resonance: 9 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('arcane', 'DHT - Dark Pluck', { osc1_shape: 20, osc2_shape: 60, osc2_pitch: -12, osc2_fine: -5, mode: 'pm', mod_amount: 25, fold: 0, spread: 15, ampEnv: { attack: 0.001, decay: 0.1, sustain: 0, release: 0.08 }, filter: { type: 'lowpass', cutoff: 1200, resonance: 6 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('arcane', 'DHT - Dirty Saw', { osc1_shape: 100, osc2_shape: 95, osc2_pitch: 0, osc2_fine: 5, mode: 'add', mod_amount: 0, fold: 50, spread: 30, ampEnv: { attack: 0.001, decay: 0.25, sustain: 0, release: 0.15 }, filter: { type: 'lowpass', cutoff: 3500, resonance: 6 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('arcane', 'DHT - Space Alarm', { osc1_shape: 0, osc2_shape: 100, osc2_pitch: 12, osc2_fine: 0, mode: 'ring', mod_amount: 100, fold: 0, spread: 0, ampEnv: { attack: 0.001, decay: 0.1, sustain: 0, release: 0.1 }, filter: { type: 'lowpass', cutoff: 6000, resonance: 4 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('arcane', 'DHT - Riser FX', { osc1_shape: 50, osc2_shape: 50, osc2_pitch: 0, osc2_fine: 0, mode: 'pm', mod_amount: 80, fold: 70, spread: 100, ampEnv: { attack: 2.0, decay: 1.0, sustain: 1.0, release: 0.5 }, filter: { type: 'highpass', cutoff: 200, resonance: 5 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('arcane', 'DHT - Digital Tom', { osc1_shape: 0, osc2_shape: 10, osc2_pitch: -12, osc2_fine: 0, mode: 'pm', mod_amount: 30, fold: 0, spread: 0, ampEnv: { attack: 0.001, decay: 0.12, sustain: 0, release: 0.1 }, filter: { type: 'lowpass', cutoff: 1500, resonance: 7 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('arcane', 'DHT - Hollow Drone', { osc1_shape: 15, osc2_shape: 85, osc2_pitch: 0, osc2_fine: 2, mode: 'pm', mod_amount: 10, fold: 0, spread: 50, ampEnv: { attack: 0.5, decay: 1.5, sustain: 0.8, release: 2.0 }, filter: { type: 'lowpass', cutoff: 800, resonance: 8 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
];

const ARTIFICE_PRESETS: InstrumentPreset[] = [
    createPreset('artifice', 'DHT - Noise Hit', { osc1_shape: 0, osc2_shape: 0, osc2_pitch: 0, osc2_fine: 0, fm_amount: 0, osc_mix: -100, noise_level: 100, ampEnv: { attack: 0.001, decay: 0.09, sustain: 0, release: 0.05 }, filterEnv: { attack: 0.001, decay: 0.05, sustain: 0, release: 0.1 }, filterEnvAmount: 8000, filter_mode: 'bp_bp_p', filter_cutoff: 5000, filter_res: 12, filter_spread: 24, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('artifice', 'DHT - FM Perc', { osc1_shape: 10, osc2_shape: 90, osc2_pitch: 12, osc2_fine: 0, fm_amount: 60, osc_mix: 0, noise_level: 0, ampEnv: { attack: 0.001, decay: 0.15, sustain: 0, release: 0.1 }, filterEnv: { attack: 0.001, decay: 0.1, sustain: 0, release: 0.1 }, filterEnvAmount: 4000, filter_mode: 'lp_hp_s', filter_cutoff: 3000, filter_res: 5, filter_spread: -12, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('artifice', 'DHT - Gritty Stab', { osc1_shape: 80, osc2_shape: 70, osc2_pitch: 7, osc2_fine: 0, fm_amount: 10, osc_mix: 30, noise_level: 25, ampEnv: { attack: 0.001, decay: 0.2, sustain: 0, release: 0.15 }, filterEnv: { attack: 0.01, decay: 0.15, sustain: 0, release: 0.1 }, filterEnvAmount: 5000, filter_mode: 'lp_hp_p', filter_cutoff: 2500, filter_res: 9, filter_spread: -18, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('artifice', 'DHT - Filtered Chord', { osc1_shape: 20, osc2_shape: 80, osc2_pitch: 4, osc2_fine: 0, fm_amount: 0, osc_mix: -20, noise_level: 10, ampEnv: { attack: 0.001, decay: 0.3, sustain: 0, release: 0.2 }, filterEnv: { attack: 0.05, decay: 0.25, sustain: 0, release: 0.2 }, filterEnvAmount: 3000, filter_mode: 'lp_hp_p', filter_cutoff: 1500, filter_res: 10, filter_spread: 0, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('artifice', 'DHT - Reso Drone Hit', { osc1_shape: 50, osc2_shape: 50, osc2_pitch: 0, osc2_fine: 0, fm_amount: 0, osc_mix: 0, noise_level: 80, ampEnv: { attack: 0.001, decay: 0.5, sustain: 0, release: 0.4 }, filterEnv: { attack: 0.001, decay: 0.4, sustain: 0, release: 0.2 }, filterEnvAmount: 10000, filter_mode: 'bp_bp_p', filter_cutoff: 1000, filter_res: 25, filter_spread: 3, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('artifice', 'DHT - Raw Saw', { osc1_shape: 100, osc2_shape: 100, osc2_pitch: 0, osc2_fine: 3, fm_amount: 0, osc_mix: 0, noise_level: 10, ampEnv: { attack: 0.001, decay: 0.2, sustain: 0, release: 0.1 }, filterEnv: { attack: 0.001, decay: 0.1, sustain: 0, release: 0.1 }, filterEnvAmount: 0, filter_mode: 'lp_hp_s', filter_cutoff: 4000, filter_res: 3, filter_spread: 0, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('artifice', 'DHT - Industrial Clap', { osc1_shape: 0, osc2_shape: 0, osc2_pitch: 0, osc2_fine: 0, fm_amount: 0, osc_mix: 0, noise_level: 100, ampEnv: { attack: 0.001, decay: 0.08, sustain: 0, release: 0.05 }, filterEnv: { attack: 0.001, decay: 0.08, sustain: 0, release: 0.1 }, filterEnvAmount: 9000, filter_mode: 'bp_bp_p', filter_cutoff: 2500, filter_res: 15, filter_spread: 36, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('artifice', 'DHT - Detuned Pad', { osc1_shape: 20, osc2_shape: 25, osc2_pitch: 0, osc2_fine: 8, fm_amount: 5, osc_mix: -15, noise_level: 15, ampEnv: { attack: 0.3, decay: 1.2, sustain: 0.6, release: 0.8 }, filterEnv: { attack: 0.5, decay: 1.0, sustain: 0, release: 0.5 }, filterEnvAmount: 1500, filter_mode: 'lp_hp_p', filter_cutoff: 1200, filter_res: 8, filter_spread: 24, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('artifice', 'DHT - Acid Squelch', { osc1_shape: 90, osc2_shape: 0, osc2_pitch: -12, osc2_fine: 0, fm_amount: 0, osc_mix: -100, noise_level: 0, ampEnv: { attack: 0.001, decay: 0.2, sustain: 0, release: 0.1 }, filterEnv: { attack: 0.001, decay: 0.12, sustain: 0, release: 0.1 }, filterEnvAmount: 8000, filter_mode: 'lp_hp_s', filter_cutoff: 400, filter_res: 18, filter_spread: 0, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('artifice', 'DHT - Space Junk', { osc1_shape: 50, osc2_shape: 50, osc2_pitch: 19, osc2_fine: 50, fm_amount: 80, osc_mix: 0, noise_level: 40, ampEnv: { attack: 0.001, decay: 0.1, sustain: 0, release: 0.1 }, filterEnv: { attack: 0.001, decay: 0.05, sustain: 0, release: 0.1 }, filterEnvAmount: 10000, filter_mode: 'bp_bp_p', filter_cutoff: 8000, filter_res: 20, filter_spread: 48, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
];

const SHIFT_PRESETS: InstrumentPreset[] = [
    createPreset('shift', 'DHT - Wavetable Zap', { pitch: 60, table: 3, position: 80, bend: 90, twist: 40, ampEnv: { attack: 0.001, decay: 0.1, sustain: 0, release: 0.08 }, filter: { type: 'bandpass', cutoff: 3500, resonance: 10 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('shift', 'DHT - Grainy Hit', { pitch: 48, table: 1, position: 30, bend: 50, twist: 80, ampEnv: { attack: 0.001, decay: 0.15, sustain: 0, release: 0.1 }, filter: { type: 'highpass', cutoff: 1000, resonance: 4 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('shift', 'DHT - Formant Stab', { pitch: 48, table: 2, position: 50, bend: 10, twist: 10, ampEnv: { attack: 0.001, decay: 0.2, sustain: 0, release: 0.15 }, filter: { type: 'lowpass', cutoff: 2200, resonance: 7 }, lfo1: { ...NEUTRAL_LFO, destination: 'shift.position', rate: 0.2, depth: 400 }, lfo2: NEUTRAL_LFO }),
    createPreset('shift', 'DHT - Metallic Pluck', { pitch: 72, table: 0, position: 10, bend: 70, twist: 90, ampEnv: { attack: 0.001, decay: 0.25, sustain: 0, release: 0.2 }, filter: { type: 'highpass', cutoff: 800, resonance: 2 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('shift', 'DHT - Twisted Bass', { pitch: 36, table: 3, position: 0, bend: 40, twist: 100, ampEnv: { attack: 0.001, decay: 0.18, sustain: 0, release: 0.1 }, filter: { type: 'lowpass', cutoff: 700, resonance: 9 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('shift', 'DHT - Scanning Drone', { pitch: 36, table: 1, position: 0, bend: 0, twist: 0, ampEnv: { attack: 1.0, decay: 2.0, sustain: 1.0, release: 2.0 }, filter: { type: 'lowpass', cutoff: 1200, resonance: 6 }, lfo1: { ...NEUTRAL_LFO, destination: 'shift.position', rate: 0.05, depth: 1000 }, lfo2: NEUTRAL_LFO }),
    createPreset('shift', 'DHT - Classic Hoover', { pitch: 48, table: 0, position: 0, bend: 0, twist: 0, ampEnv: { attack: 0.05, decay: 0.5, sustain: 0.8, release: 0.3 }, filter: { type: 'lowpass', cutoff: 4000, resonance: 4 }, lfo1: { ...NEUTRAL_LFO, destination: 'pan', rate: 6, depth: 300 }, lfo2: NEUTRAL_LFO }),
    createPreset('shift', 'DHT - Spectral Perc', { pitch: 65, table: 1, position: 70, bend: 20, twist: 70, ampEnv: { attack: 0.001, decay: 0.08, sustain: 0, release: 0.05 }, filter: { type: 'highpass', cutoff: 1500, resonance: 3 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('shift', 'DHT - Vocal Bass', { pitch: 40, table: 2, position: 25, bend: 80, twist: 10, ampEnv: { attack: 0.001, decay: 0.2, sustain: 0, release: 0.1 }, filter: { type: 'lowpass', cutoff: 1000, resonance: 8 }, lfo1: { ...NEUTRAL_LFO, destination: 'shift.position', waveform: 'sawtooth', rate: 8, depth: 200, retrigger: true }, lfo2: NEUTRAL_LFO }),
    createPreset('shift', 'DHT - Modern Saw Lead', { pitch: 60, table: 3, position: 0, bend: 0, twist: 0, ampEnv: { attack: 0.001, decay: 0.3, sustain: 0, release: 0.2 }, filter: { type: 'lowpass', cutoff: 8000, resonance: 2 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
];

const RESON_PRESETS: InstrumentPreset[] = [
    createPreset('reson', 'DHT - Wood Block', { pitch: 72, structure: 80, brightness: 12000, decay: 0.9, material: 80, exciter_type: 'impulse', ampEnv: { attack: 0.001, decay: 0.05, sustain: 0, release: 0.04 }, filter: { type: 'lowpass', cutoff: 18000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('reson', 'DHT - Metal Pipe', { pitch: 65, structure: 20, brightness: 10000, decay: 0.98, material: 10, exciter_type: 'impulse', ampEnv: { attack: 0.001, decay: 0.3, sustain: 0, release: 0.2 }, filter: { type: 'highpass', cutoff: 400, resonance: 2 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('reson', 'DHT - Damped Hit', { pitch: 55, structure: 50, brightness: 6000, decay: 0.92, material: 90, exciter_type: 'noise', ampEnv: { attack: 0.001, decay: 0.08, sustain: 0, release: 0.06 }, filter: { type: 'lowpass', cutoff: 7000, resonance: 3 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('reson', 'DHT - Glassy Ping', { pitch: 84, structure: 10, brightness: 15000, decay: 0.96, material: 30, exciter_type: 'impulse', ampEnv: { attack: 0.001, decay: 0.2, sustain: 0, release: 0.15 }, filter: { type: 'lowpass', cutoff: 20000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('reson', 'DHT - Scrape', { pitch: 50, structure: 90, brightness: 8000, decay: 0.99, material: 60, exciter_type: 'noise', ampEnv: { attack: 0.001, decay: 0.12, sustain: 0, release: 0.1 }, filter: { type: 'bandpass', cutoff: 3000, resonance: 8 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('reson', 'DHT - Rubber Mallet', { pitch: 60, structure: 60, brightness: 4000, decay: 0.94, material: 95, exciter_type: 'impulse', ampEnv: { attack: 0.001, decay: 0.15, sustain: 0, release: 0.1 }, filter: { type: 'lowpass', cutoff: 10000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('reson', 'DHT - Alien Tom', { pitch: 45, structure: 0, brightness: 5000, decay: 0.95, material: 50, exciter_type: 'impulse', ampEnv: { attack: 0.001, decay: 0.1, sustain: 0, release: 0.08 }, filter: { type: 'lowpass', cutoff: 18000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('reson', 'DHT - Long Gong', { pitch: 36, structure: 40, brightness: 9000, decay: 0.995, material: 20, exciter_type: 'impulse', ampEnv: { attack: 0.001, decay: 2.0, sustain: 0, release: 1.5 }, filter: { type: 'lowpass', cutoff: 20000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('reson', 'DHT - Noise Burst', { pitch: 80, structure: 100, brightness: 18000, decay: 0.8, material: 0, exciter_type: 'noise', ampEnv: { attack: 0.001, decay: 0.05, sustain: 0, release: 0.05 }, filter: { type: 'highpass', cutoff: 5000, resonance: 2 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('reson', 'DHT - Dub Marimba', { pitch: 60, structure: 70, brightness: 7000, decay: 0.92, material: 85, exciter_type: 'impulse', ampEnv: { attack: 0.001, decay: 0.1, sustain: 0, release: 0.1 }, filter: { type: 'lowpass', cutoff: 12000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
];

const ALLOY_PRESETS: InstrumentPreset[] = [
    createPreset('alloy', 'DHT - FM Bell', { pitch: 72, ratio: 3.5, feedback: 20, mod_level: 40, mod_attack: 0.001, mod_decay: 0.15, ampEnv: { attack: 0.001, decay: 0.3, sustain: 0, release: 0.2 }, filter: { type: 'highpass', cutoff: 300, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('alloy', 'DHT - Clang', { pitch: 58, ratio: 2.8, feedback: 60, mod_level: 80, mod_attack: 0.001, mod_decay: 0.08, ampEnv: { attack: 0.001, decay: 0.1, sustain: 0, release: 0.08 }, filter: { type: 'bandpass', cutoff: 2000, resonance: 6 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('alloy', 'DHT - Digital Pluck', { pitch: 60, ratio: 1.0, feedback: 5, mod_level: 90, mod_attack: 0.001, mod_decay: 0.05, ampEnv: { attack: 0.001, decay: 0.12, sustain: 0, release: 0.1 }, filter: { type: 'lowpass', cutoff: 15000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('alloy', 'DHT - Bass Punch', { pitch: 36, ratio: 0.5, feedback: 40, mod_level: 70, mod_attack: 0.001, mod_decay: 0.1, ampEnv: { attack: 0.001, decay: 0.18, sustain: 0, release: 0.1 }, filter: { type: 'lowpass', cutoff: 900, resonance: 4 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('alloy', 'DHT - Feedback Hit', { pitch: 50, ratio: 1.414, feedback: 95, mod_level: 20, mod_attack: 0.001, mod_decay: 0.2, ampEnv: { attack: 0.001, decay: 0.25, sustain: 0, release: 0.2 }, filter: { type: 'lowpass', cutoff: 6000, resonance: 3 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('alloy', 'DHT - Glassy FM', { pitch: 84, ratio: 4.2, feedback: 10, mod_level: 50, mod_attack: 0.001, mod_decay: 0.2, ampEnv: { attack: 0.001, decay: 0.4, sustain: 0, release: 0.3 }, filter: { type: 'highpass', cutoff: 1000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('alloy', 'DHT - Gritty Perc', { pitch: 62, ratio: 0.7, feedback: 80, mod_level: 85, mod_attack: 0.001, mod_decay: 0.06, ampEnv: { attack: 0.001, decay: 0.08, sustain: 0, release: 0.06 }, filter: { type: 'bandpass', cutoff: 3000, resonance: 8 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('alloy', 'DHT - Soft Mallet', { pitch: 60, ratio: 2.0, feedback: 0, mod_level: 30, mod_attack: 0.001, mod_decay: 0.1, ampEnv: { attack: 0.001, decay: 0.2, sustain: 0, release: 0.15 }, filter: { type: 'lowpass', cutoff: 8000, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('alloy', 'DHT - High Bell', { pitch: 96, ratio: 3.0, feedback: 15, mod_level: 25, mod_attack: 0.001, mod_decay: 0.08, ampEnv: { attack: 0.001, decay: 0.15, sustain: 0, release: 0.1 }, filter: { type: 'highpass', cutoff: 1500, resonance: 1 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
    createPreset('alloy', 'DHT - Angry FM Bass', { pitch: 36, ratio: 0.5, feedback: 90, mod_level: 90, mod_attack: 0.001, mod_decay: 0.12, ampEnv: { attack: 0.001, decay: 0.2, sustain: 0, release: 0.15 }, filter: { type: 'lowpass', cutoff: 600, resonance: 6 }, lfo1: NEUTRAL_LFO, lfo2: NEUTRAL_LFO }),
];


export const TECHNO_PRESET_LIBRARY = {
    kick: KICK_PRESETS,
    hat: HAT_PRESETS,
    arcane: ARCANE_PRESETS,
    ruin: RUIN_PRESETS,
    artifice: ARTIFICE_PRESETS,
    shift: SHIFT_PRESETS,
    reson: RESON_PRESETS,
    alloy: ALLOY_PRESETS,
};